version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: androlabserver
    volumes:
      - ./src:/app
    ports:
      - 8888:8888
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
